In [89]:
import numpy as np
import sympy as sp

# Define the given values
expected_returns = np.array([0.06, 0.12])  # Expected returns for asset 1 and 2
std_devs = np.array([0.15, 0.25])          # Standard deviations for asset 1 and 2
correlation = 0.30                         # Correlation between the two assets
risk_free_rate = 0.02                      # Risk-free interest rate

# Calculate the covariance matrix
cov_matrix = np.array([
    [std_devs[0]**2, correlation * std_devs[0] * std_devs[1]],
    [correlation * std_devs[0] * std_devs[1], std_devs[1]**2]
])

# Compute E(R) - rf * 1
excess_returns = expected_returns - risk_free_rate

# Calculate the inverse of the covariance matrix
inv_cov_matrix = np.linalg.inv(cov_matrix)

# Calculate weights for the tangency portfolio
ones = np.ones(len(expected_returns))
weights = np.dot(inv_cov_matrix, excess_returns) / np.dot(ones, np.dot(inv_cov_matrix, excess_returns))

weights, cov_matrix


(array([0.43307087, 0.56692913]),
 array([[0.0225 , 0.01125],
        [0.01125, 0.0625 ]]))

In [90]:
sp.Matrix((weights*20).round(2))

Matrix([
[ 8.66],
[11.34]])

In [91]:
sp.Matrix(inv_cov_matrix.round(3))

Matrix([
[ 48.84, -8.791],
[-8.791, 17.582]])

In [92]:
sp.Matrix(excess_returns.round(3))

Matrix([
[0.04],
[ 0.1]])

In [93]:
sp.Matrix(cov_matrix.round(3))

Matrix([
[0.022, 0.011],
[0.011, 0.062]])

# ii

In [94]:
# Constants and previous results
target_expected_return = 0.08

# Tangency portfolio weights from previous calculations
weights_tangency = weights

# Calculate scaling factor k
k = (target_expected_return - risk_free_rate) / (weights_tangency.dot(excess_returns))

# Calculate new scaled weights
new_weights = k * weights_tangency

# Calculate cash allocation
cash_allocation = 1 - np.sum(new_weights)

# Display the results
new_weights, cash_allocation, k

(array([0.35106383, 0.45957447]), 0.18936170212765946, 0.8106382978723405)

In [95]:
sp.Matrix((new_weights*20).round(2))

Matrix([
[7.02],
[9.19]])

In [96]:
cash_allocation*20

3.787234042553189

In [97]:
# Given covariance matrix from previous discussions
Sigma = np.array([[0.0225, 0.01125], [0.01125, 0.0625]])

# Calculate the portfolio standard deviation
portfolio_std_dev = np.sqrt(new_weights.T @ Sigma @ new_weights)
portfolio_std_dev


0.1400132972408525

In [98]:
# Calculate the actual expected return using the new weights
actual_expected_return = new_weights.dot(expected_returns) + cash_allocation * risk_free_rate
actual_expected_return


0.07999999999999999

# iii

In [99]:
# Constants and previous results
target_expected_return = 0.15

# Calculate scaling factor k
k = (target_expected_return - risk_free_rate) / (weights_tangency.dot(excess_returns))

# Calculate new scaled weights
new_weights = k * weights_tangency

# Calculate cash allocation
cash_allocation = 1 - np.sum(new_weights)

# Display the results
new_weights, cash_allocation, k

(array([0.7606383 , 0.99574468]), -0.7563829787234044, 1.7563829787234047)

In [100]:
sp.Matrix((new_weights*20).round(2))

Matrix([
[15.21],
[19.91]])

In [101]:
cash_allocation*20

-15.127659574468089

In [102]:
cash_allocation

-0.7563829787234044

In [103]:
# Calculate the portfolio standard deviation
portfolio_std_dev = np.sqrt(new_weights.T @ Sigma @ new_weights)
portfolio_std_dev


0.3033621440218472

# iv

In [104]:
# Calculate the current standard deviation of the tangency portfolio
current_std_dev = np.sqrt(weights_tangency.T @ Sigma @ weights_tangency)

# Desired standard deviation
target_std_dev = 0.20

# Scaling factor to achieve target standard deviation
scaling_factor = target_std_dev / current_std_dev

# Scale the weights to achieve the target standard deviation
scaled_weights = scaling_factor * weights_tangency

# Calculate the expected return of the scaled portfolio
scaled_expected_return = scaled_weights.dot(expected_returns)
wcash = 1-scaled_weights[0] - scaled_weights[1]
scaled_weights, scaled_expected_return, wcash


(array([0.50147213, 0.6564726 ]), 0.10886503990595225, -0.1579447293179177)

In [105]:
sp.Matrix((scaled_weights*20).round(3))

Matrix([
[10.029],
[13.129]])

In [106]:
wcash*20

-3.158894586358354

In [107]:
scaled_expected_return

0.10886503990595225

In [108]:
net_expected_return = np.dot(scaled_weights, expected_returns) + wcash * risk_free_rate

# Print the results
print("Scaled Weights:", scaled_weights)
print("Cash Weight (w_cash):", wcash)
print("Net Expected Return:", net_expected_return)
print("Net Expected Return:", net_expected_return*20)

Scaled Weights: [0.50147213 0.6564726 ]
Cash Weight (w_cash): -0.1579447293179177
Net Expected Return: 0.1057061453195939
Net Expected Return: 2.114122906391878


# v

In [109]:
# Desired standard deviation
target_std_dev = 0.30

# Scaling factor to achieve target standard deviation
scaling_factor = target_std_dev / current_std_dev

# Scale the weights to achieve the target standard deviation
scaled_weights = scaling_factor * weights_tangency

# Calculate the expected return of the scaled portfolio
scaled_expected_return = scaled_weights.dot(expected_returns)
wcash = 1-scaled_weights[0] - scaled_weights[1]
scaled_weights, scaled_expected_return, wcash

(array([0.75220819, 0.9847089 ]), 0.16329755985892835, -0.7369170939768762)

In [110]:
sp.Matrix((scaled_weights).round(3))

Matrix([
[0.752],
[0.985]])

In [111]:
sp.Matrix((scaled_weights*20).round(3))

Matrix([
[15.044],
[19.694]])

In [112]:
net_expected_return = np.dot(scaled_weights, expected_returns) + wcash * risk_free_rate

# Print the results
print("Scaled Weights:", scaled_weights)
print("Cash Weight (w_cash):", wcash)
print("Net Expected Return:", net_expected_return)
print("Net Expected Return:", net_expected_return*20)

Scaled Weights: [0.75220819 0.9847089 ]
Cash Weight (w_cash): -0.7369170939768762
Net Expected Return: 0.14855921797939084
Net Expected Return: 2.971184359587817


In [113]:
wcash*20

-14.738341879537524

# vi

In [114]:
# Define the given values
risk_free_rate = 0.025                     # Risk-free interest rate

# Compute E(R) - rf * 1
excess_returns = expected_returns - risk_free_rate

# Calculate weights for the tangency portfolio
ones = np.ones(len(expected_returns))
weights = np.dot(inv_cov_matrix, excess_returns) / np.dot(ones, np.dot(inv_cov_matrix, excess_returns))


In [115]:
weights, cov_matrix

(array([0.39082969, 0.60917031]),
 array([[0.0225 , 0.01125],
        [0.01125, 0.0625 ]]))

In [118]:
sp.Matrix(weights.round(3))

Matrix([
[0.391],
[0.609]])

In [119]:
# Constants and previous results
target_expected_return = 0.08

# Tangency portfolio weights from previous calculations
weights_tangency = weights

# Calculate scaling factor k
k = (target_expected_return - risk_free_rate) / (weights_tangency.dot(excess_returns))

# Calculate new scaled weights
new_weights = k * weights_tangency

# Calculate cash allocation
cash_allocation = 1 - np.sum(new_weights)

# Display the results
new_weights, cash_allocation, k

(array([0.30042722, 0.46826366]), 0.23130912419896255, 0.7686908758010375)

In [120]:
sp.Matrix((new_weights*20).round(3))

Matrix([
[6.009],
[9.365]])

In [121]:
sp.Matrix((new_weights).round(3))

Matrix([
[  0.3],
[0.468]])

In [122]:
cash_allocation*20

4.626182483979251

In [123]:
# Calculate the current standard deviation of the tangency portfolio
current_std_dev = np.sqrt(weights_tangency.T @ Sigma @ weights_tangency)

# Desired standard deviation
target_std_dev = 0.20

# Scaling factor to achieve target standard deviation
scaling_factor = target_std_dev / current_std_dev

# Scale the weights to achieve the target standard deviation
scaled_weights = scaling_factor * weights_tangency

# Calculate the expected return of the scaled portfolio
scaled_expected_return = scaled_weights.dot(expected_returns)
wcash = 1-scaled_weights[0] - scaled_weights[1]
scaled_weights, scaled_expected_return, wcash


(array([0.43705174, 0.68121472]), 0.10796887047735776, -0.11826645587132179)

In [124]:
sp.Matrix(scaled_weights.round(3))

Matrix([
[0.437],
[0.681]])

In [125]:
sp.Matrix((scaled_weights*20).round(3))

Matrix([
[ 8.741],
[13.624]])

In [126]:
wcash*20

-2.3653291174264357