## Exercise 1

In [1]:
import numpy as np

# Define S
S = np.array([
    [1,      -0.525,  0.375],
    [-0.525,  2.25,   0.1875],
    [0.375,   0.1875, 6.25]
])

# Extract diagonal into a vector
v = np.diag(S)

# Element-wise square root
v_sqrt = np.sqrt(v)

# Create diagonal matrix D
D = np.diag(v_sqrt)

print("S =\n", S)
print("\nv =", v)
print("\nv_sqrt =", v_sqrt)
print("\nD =\n", D)


S =
 [[ 1.     -0.525   0.375 ]
 [-0.525   2.25    0.1875]
 [ 0.375   0.1875  6.25  ]]

v = [1.   2.25 6.25]

v_sqrt = [1.  1.5 2.5]

D =
 [[1.  0.  0. ]
 [0.  1.5 0. ]
 [0.  0.  2.5]]


In [2]:
# Element-wise inverse of D (since D is diagonal, just invert the diagonal entries)
Dinv = np.diag(1 / v_sqrt)

# Multiply S from left and right by Dinv
result = Dinv @ S @ Dinv

print("Dinv =\n", Dinv)
print("\nResult =\n", result)


Dinv =
 [[1.         0.         0.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.4       ]]

Result =
 [[ 1.   -0.35  0.15]
 [-0.35  1.    0.05]
 [ 0.15  0.05  1.  ]]


In [3]:
import numpy as np
import sympy as sp

# Original S in sympy
S = sp.Matrix([
    [1,      -0.525,  0.375],
    [-0.525,  2.25,   0.1875],
    [0.375,   0.1875, 6.25]
])

# Diagonal elements
v = S.diagonal()

# Element-wise square root
v_sqrt = [sp.sqrt(x) for x in v]

# D matrix
D = sp.diag(*v_sqrt)

# Dinv
Dinv = sp.diag(*[1/x for x in v_sqrt])

# Result = Dinv * S * Dinv
result = Dinv * S * Dinv

# Get LaTeX source code
latex_Dinv = sp.latex(Dinv)
latex_result = sp.latex(result)

print("LaTeX for Dinv:")
print(latex_Dinv)

print("\nLaTeX for result:")
print(latex_result)


LaTeX for Dinv:
\left[\begin{matrix}1 & 0 & 0\\0 & 0.666666666666667 & 0\\0 & 0 & 0.4\end{matrix}\right]

LaTeX for result:
\left[\begin{matrix}1 & -0.35 & 0.15\\-0.35 & 1.0 & 0.05\\0.15 & 0.05 & 1.0\end{matrix}\right]


In [11]:
sp.print_latex(Dinv, mode="equation")

\begin{equation}\left[\begin{matrix}1 & 0 & 0\\0 & 0.666666666666667 & 0\\0 & 0 & 0.4\end{matrix}\right]\end{equation}


In [15]:
sp.print_latex(result, mode="equation")

\begin{equation}\left[\begin{matrix}1 & -0.35 & 0.15\\-0.35 & 1.0 & 0.05\\0.15 & 0.05 & 1.0\end{matrix}\right]\end{equation}


## Exercise 2

In [ ]:
import pandas as pd

# File path
file_path = "indeces-jul26-aug9-2012.xlsx"

# Read Excel file into a DataFrame
df = pd.read_excel(file_path)
df.columns = df.columns.str.strip()
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")
# Show first few rows
df.head()


Date  Dow Jones   NASDAQ  S&P 500
0 2012-07-26   12887.93  2893.25  1360.02
1 2012-07-27   13075.66  2958.09  1385.97
2 2012-07-30   13073.01  2945.84  1385.30
3 2012-07-31   13008.68  2939.52  1379.32
4 2012-08-01   12976.13  2920.21  1375.32

In [45]:
# Calculate percentage returns
for col in ["Dow Jones", "NASDAQ", "S&P 500"]:
    df[f"{col} % Return"] = df[col].pct_change() * 100
    df[f"{col} Log Return"] = np.log(df[col] / df[col].shift(1))

df.head()

Date  Dow Jones   NASDAQ  S&P 500  Dow Jones % Return  \
0 2012-07-26   12887.93  2893.25  1360.02                 NaN   
1 2012-07-27   13075.66  2958.09  1385.97            1.456634   
2 2012-07-30   13073.01  2945.84  1385.30           -0.020267   
3 2012-07-31   13008.68  2939.52  1379.32           -0.492083   
4 2012-08-01   12976.13  2920.21  1375.32           -0.250218   

   Dow Jones Log Return  NASDAQ % Return  NASDAQ Log Return  S&P 500 % Return  \
0                   NaN              NaN                NaN               NaN   
1              0.014461         2.241078           0.022163          1.908060   
2             -0.000203        -0.414119          -0.004150         -0.048342   
3             -0.004933        -0.214540          -0.002148         -0.431675   
4             -0.002505        -0.656910          -0.006591         -0.289998   

   S&P 500 Log Return  
0                 NaN  
1            0.018901  
2           -0.000484  
3           -0.004326  
4           -0.002904

In [ ]:
# show the percentage returns only
print(df[["Date", "Dow Jones % Return", "NASDAQ % Return", "S&P 500 % Return"]].to_latex(escape=True, index=False))


\begin{tabular}{lrrr}
\toprule
Date & Dow Jones \% Return & NASDAQ \% Return & S\&P 500 \% Return \\
\midrule
2012-07-26 & NaN & NaN & NaN \\
2012-07-27 & 1.456634 & 2.241078 & 1.908060 \\
2012-07-30 & -0.020267 & -0.414119 & -0.048342 \\
2012-07-31 & -0.492083 & -0.214540 & -0.431675 \\
2012-08-01 & -0.250218 & -0.656910 & -0.289998 \\
2012-08-02 & -0.749453 & -0.357509 & -0.750371 \\
2012-08-03 & 1.687181 & 1.997752 & 1.904029 \\
2012-08-06 & 0.162948 & 0.741602 & 0.232928 \\
2012-08-07 & 0.389479 & 0.867919 & 0.510676 \\
2012-08-08 & 0.053461 & -0.152859 & 0.062083 \\
2012-08-09 & -0.079313 & 0.245413 & 0.041363 \\
\bottomrule
\end{tabular}



In [47]:
# Extract the percentage returns columns
returns_df = df[["Dow Jones % Return", "NASDAQ % Return", "S&P 500 % Return"]]

# Compute the covariance matrix
cov_matrix = returns_df.cov()

# Rename rows/columns to tickers
tickers = ["Dow Jones", "NASDAQ", "S&P 500"]
cov_df = pd.DataFrame(cov_matrix.values, index=tickers, columns=tickers)

cov_df


Dow Jones    NASDAQ   S&P 500
Dow Jones   0.617416  0.742765  0.711061
NASDAQ      0.742765  1.036670  0.879881
S&P 500     0.711061  0.879881  0.826366

In [49]:
print(cov_df.to_latex(escape=True, index=True))

\begin{tabular}{lrrr}
\toprule
 & Dow Jones & NASDAQ & S\&P 500 \\
\midrule
Dow Jones & 0.617416 & 0.742765 & 0.711061 \\
NASDAQ & 0.742765 & 1.036670 & 0.879881 \\
S\&P 500 & 0.711061 & 0.879881 & 0.826366 \\
\bottomrule
\end{tabular}



In [50]:
print(df[["Date", "Dow Jones Log Return", "NASDAQ Log Return", "S&P 500 Log Return"]].to_latex(escape=True, index=False))

\begin{tabular}{lrrr}
\toprule
Date & Dow Jones Log Return & NASDAQ Log Return & S\&P 500 Log Return \\
\midrule
2012-07-26 & NaN & NaN & NaN \\
2012-07-27 & 0.014461 & 0.022163 & 0.018901 \\
2012-07-30 & -0.000203 & -0.004150 & -0.000484 \\
2012-07-31 & -0.004933 & -0.002148 & -0.004326 \\
2012-08-01 & -0.002505 & -0.006591 & -0.002904 \\
2012-08-02 & -0.007523 & -0.003581 & -0.007532 \\
2012-08-03 & 0.016731 & 0.019781 & 0.018861 \\
2012-08-06 & 0.001628 & 0.007389 & 0.002327 \\
2012-08-07 & 0.003887 & 0.008642 & 0.005094 \\
2012-08-08 & 0.000534 & -0.001530 & 0.000621 \\
2012-08-09 & -0.000793 & 0.002451 & 0.000414 \\
\bottomrule
\end{tabular}



In [51]:
# Extract the log returns columns
returns_df = df[["Dow Jones Log Return", "NASDAQ Log Return", "S&P 500 Log Return"]]

# Compute the covariance matrix
cov_matrix = returns_df.cov()

# Rename rows/columns to tickers
tickers = ["Dow Jones", "NASDAQ", "S&P 500"]
cov_df = pd.DataFrame(cov_matrix.values, index=tickers, columns=tickers)

cov_df

Dow Jones    NASDAQ   S&P 500
Dow Jones   0.000061  0.000073  0.000070
NASDAQ      0.000073  0.000102  0.000087
S&P 500     0.000070  0.000087  0.000081

In [52]:
print(cov_df.to_latex(escape=True, index=True))

\begin{tabular}{lrrr}
\toprule
 & Dow Jones & NASDAQ & S\&P 500 \\
\midrule
Dow Jones & 0.000061 & 0.000073 & 0.000070 \\
NASDAQ & 0.000073 & 0.000102 & 0.000087 \\
S\&P 500 & 0.000070 & 0.000087 & 0.000081 \\
\bottomrule
\end{tabular}



## Exercise 3

In [53]:
import numpy as np
import pandas as pd

# Parameters
r, T = 0.06, 0.5
K = 40
S_T = np.array([30, 35, 40, 42, 45, 50], dtype=float)

# Labels as requested
cols = [r'$\omega_1$', r'$\omega_2$', r'$\omega_3$', r'$\omega_4$', r'$\omega_5$', r'$\omega_6$']
idx  = ['P_0', 'P_1', 'P_2', 'P_3']  # P_0=cash, P_1=asset, P_2=ATM call, P_3=ATM put

# Payoffs at T=6 months
cash = np.full(S_T.shape, np.exp(r*T))      # e^{0.03}
asset = S_T
call = np.maximum(S_T - K, 0.0)
put  = np.maximum(K - S_T, 0.0)

df = pd.DataFrame([cash, asset, call, put], index=idx, columns=cols)

# Optional: meanings of indices
idx_meaning = pd.DataFrame(
    {'Security': [
        'Cash (riskless), pays e^{0.03} at T',
        'Underlying asset S_T',
        'Six-month ATM call, K=40',
        'Six-month ATM put, K=40'
    ]},
    index=idx
)

df, idx_meaning


(     $\omega_1$  $\omega_2$  $\omega_3$  $\omega_4$  $\omega_5$  $\omega_6$
 P_0    1.030455    1.030455    1.030455    1.030455    1.030455    1.030455
 P_1   30.000000   35.000000   40.000000   42.000000   45.000000   50.000000
 P_2    0.000000    0.000000    0.000000    2.000000    5.000000   10.000000
 P_3   10.000000    5.000000    0.000000    0.000000    0.000000    0.000000,
                                 Security
 P_0  Cash (riskless), pays e^{0.03} at T
 P_1                 Underlying asset S_T
 P_2             Six-month ATM call, K=40
 P_3              Six-month ATM put, K=40)

In [55]:
print(df.to_latex(escape=False, index=True))

\begin{tabular}{lrrrrrr}
\toprule
 & $\omega_1$ & $\omega_2$ & $\omega_3$ & $\omega_4$ & $\omega_5$ & $\omega_6$ \\
\midrule
P_0 & 1.030455 & 1.030455 & 1.030455 & 1.030455 & 1.030455 & 1.030455 \\
P_1 & 30.000000 & 35.000000 & 40.000000 & 42.000000 & 45.000000 & 50.000000 \\
P_2 & 0.000000 & 0.000000 & 0.000000 & 2.000000 & 5.000000 & 10.000000 \\
P_3 & 10.000000 & 5.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
\bottomrule
\end{tabular}



In [58]:
print(idx_meaning.to_latex(escape=False, index=True))

\begin{tabular}{ll}
\toprule
 & Security \\
\midrule
P_0 & Cash (riskless), pays e^{0.03} at T \\
P_1 & Underlying asset S_T \\
P_2 & Six-month ATM call, K=40 \\
P_3 & Six-month ATM put, K=40 \\
\bottomrule
\end{tabular}

