In [19]:
import numpy as np
import sympy as sp

In [16]:
# Constants
mu = np.array([0.05, 0.08, 0.11])  # expected returns
sigma = np.array([0.16, 0.20, 0.25])  # standard deviations
# Re-establish standard deviations and correlation coefficients
sigma = np.array([0.16, 0.20, 0.25])
correlation_matrix = np.array([
    [1, -0.50, -0.15],
    [-0.50, 1, -0.25],
    [-0.15, -0.25, 1]
])

# Compute the covariance matrix
covariance_matrix = np.outer(sigma, sigma) * correlation_matrix
covariance_matrix

rf = 0.02  # risk-free rate

# Covariance matrix calculation
covariance_matrix = np.outer(sigma, sigma) * correlation_matrix

# Tangency portfolio calculation
ones = np.ones(len(mu))
inverse_covariance = np.linalg.inv(covariance_matrix)
excess_returns = mu - rf

# Weight of the tangency portfolio
w_tangency = np.dot(inverse_covariance, excess_returns) / np.dot(ones, np.dot(inverse_covariance, excess_returns))

# Expected return and standard deviation of the tangency portfolio
expected_return_tangency = np.dot(w_tangency, mu)
std_dev_tangency = np.sqrt(np.dot(w_tangency, np.dot(covariance_matrix, w_tangency)))

w_tangency, expected_return_tangency, std_dev_tangency


(array([0.39174233, 0.3672995 , 0.24095817]),
 0.0754764752455233,
 0.07073962122535922)

In [17]:
sp.Matrix(covariance_matrix)

Matrix([
[0.0256,  -0.016,  -0.006],
[-0.016,    0.04, -0.0125],
[-0.006, -0.0125,  0.0625]])

In [18]:
sp.Matrix(inverse_covariance.round(4))

Matrix([
[58.3603, 26.7679, 10.9562],
[26.7679, 38.9442, 10.3586],
[10.9562, 10.3586, 19.1235]])

In [5]:
sp.Matrix(excess_returns)

Matrix([
[0.03],
[0.06],
[0.09]])

In [6]:
sp.Matrix(mu)

Matrix([
[0.05],
[0.08],
[0.11]])

In [7]:
sp.Matrix(w_tangency.round(3))

Matrix([
[0.392],
[0.367],
[0.241]])

# ii

In [8]:
# Calculate scaling factor to adjust the tangency portfolio to a 10% expected return
desired_return = 0.10
tangency_return = expected_return_tangency  # From previous calculation
scaling_factor = desired_return / tangency_return

# Scale the weights
scaled_weights = w_tangency * scaling_factor

# Calculate new expected return to verify it matches 10%
new_expected_return = np.dot(scaled_weights, mu)

# Calculate new standard deviation
new_std_dev = np.sqrt(np.dot(scaled_weights, np.dot(covariance_matrix, scaled_weights)))
cash_position = 1 - np.sum(scaled_weights)

scaled_weights, new_expected_return, new_std_dev, cash_position


(array([0.51902574, 0.48664103, 0.31924937]),
 0.1,
 0.0937240656711178,
 -0.3249161367790723)

In [9]:
sp.Matrix(scaled_weights.round(3))

Matrix([
[0.519],
[0.487],
[0.319]])

In [10]:
# Calculate scaling factor to adjust the tangency portfolio to a 10% expected return
desired_return = 0.20
tangency_return = expected_return_tangency  # From previous calculation
scaling_factor = desired_return / tangency_return

# Scale the weights
scaled_weights = w_tangency * scaling_factor

# Calculate new expected return to verify it matches 10%
new_expected_return = np.dot(scaled_weights, mu)

# Calculate new standard deviation
new_std_dev = np.sqrt(np.dot(scaled_weights, np.dot(covariance_matrix, scaled_weights)))
cash_position = 1 - np.sum(scaled_weights)

scaled_weights, new_expected_return, new_std_dev, cash_position

(array([1.03805147, 0.97328206, 0.63849874]),
 0.2,
 0.1874481313422356,
 -1.6498322735581445)

In [11]:
sp.Matrix(scaled_weights.round(3))

Matrix([
[1.038],
[0.973],
[0.638]])

In [12]:


# Tangency portfolio calculations
ones = np.ones(len(mu))
inverse_covariance = np.linalg.inv(covariance_matrix)
excess_returns = mu - 0.02

w_tangency = np.dot(inverse_covariance, excess_returns) / np.dot(ones, np.dot(inverse_covariance, excess_returns))
expected_return_tangency = np.dot(w_tangency, mu)
std_dev_tangency = np.sqrt(np.dot(w_tangency, np.dot(covariance_matrix, w_tangency)))

# Calculate scaling factor for a 20% standard deviation
desired_std_dev = 0.20
scaling_factor_max_return = desired_std_dev / std_dev_tangency

# Scale weights
max_return_weights = w_tangency * scaling_factor_max_return

# Calculate new expected return
max_return_expected = np.dot(max_return_weights, mu)

# Calculate new standard deviation to verify
max_return_std_dev = np.sqrt(np.dot(max_return_weights, np.dot(covariance_matrix, max_return_weights)))

max_return_weights, max_return_expected, max_return_std_dev


(array([1.10756129, 1.0384548 , 0.68125378]),
 0.21339236466950712,
 0.19999999999999996)

In [14]:
sp.Matrix(max_return_weights.round(3))

Matrix([
[1.108],
[1.038],
[0.681]])

In [15]:
# Calculate cash position as 1 minus the sum of scaled weights
cash_position = 1 - np.sum(max_return_weights)
cash_position


-1.8272698741607432