In [14]:
import pandas as pd
import numpy as np
from scipy import linalg
import sympy

In [23]:
A = np.mat([[1,1],[1,2]])
B = np.mat([[2,1],[1,1]])
print(sympy.Matrix(A).eigenvals())
print(sympy.Matrix(B).eigenvals())
print(A@B)


{3/2 - sqrt(5)/2: 1, sqrt(5)/2 + 3/2: 1}
{3/2 - sqrt(5)/2: 1, sqrt(5)/2 + 3/2: 1}
[[3 2]
 [4 3]]


In [12]:
linalg.eig(A)

(array([0.38196601+0.j, 2.61803399+0.j]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

In [13]:
linalg.eig(B)


(array([2.61803399+0.j, 0.38196601+0.j]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

{3/2 - sqrt(5)/2: 1, sqrt(5)/2 + 3/2: 1}

In [19]:
sympy.Matrix(B).eigenvals()

{3/2 - sqrt(5)/2: 1, sqrt(5)/2 + 3/2: 1}

In [20]:
sympy.Matrix(A@B).eigenvals()

{3 - 2*sqrt(2): 1, 2*sqrt(2) + 3: 1}

In [21]:
A@B

matrix([[3, 2],
        [4, 3]])

In [39]:
import sympy as sp

# Define matrix A
A = sp.Matrix([[41, 24], [24, 136]])

# (i) Check if A is symmetric and positive definite
is_symmetric = A == A.T
eigenvalues = A.eigenvals()
is_positive_definite = all(ev > 0 for ev in eigenvalues)

# (ii) Find matrix B such that A = B^2
B = A.pow(0.5)

# (iii) Find matrix U (upper triangular) such that A = U^T * U
U = A.cholesky()

# is_symmetric, is_positive_definite, B, U
B.simplify()
B


Matrix([
[-0.00296474288166308*sqrt(11329)*(sqrt(11329) + 177)**0.5 + 0.00296474288166308*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.353553390593274*(177 - sqrt(11329))**0.5 + 0.353553390593274*(sqrt(11329) + 177)**0.5,                                                                                           -0.00149797535073503*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.00149797535073503*sqrt(11329)*(sqrt(11329) + 177)**0.5],
[                                          -0.00149797535073503*sqrt(11329)*(177 - sqrt(11329))**0.5 + 1.42720405138895e-16*(177 - sqrt(11329))**0.5 + 0.00149797535073503*sqrt(11329)*(sqrt(11329) + 177)**0.5, -0.00296474288166307*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.353553390593274*(177 - sqrt(11329))**0.5 + 0.00296474288166308*sqrt(11329)*(sqrt(11329) + 177)**0.5 + 0.353553390593274*(sqrt(11329) + 177)**0.5]])

Matrix([
[-0.00296474288166308*sqrt(11329)*(sqrt(11329) + 177)**0.5 + 0.00296474288166308*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.353553390593274*(177 - sqrt(11329))**0.5 + 0.353553390593274*(sqrt(11329) + 177)**0.5,                                                                                           -0.00149797535073503*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.00149797535073503*sqrt(11329)*(sqrt(11329) + 177)**0.5],
[                                          -0.00149797535073503*sqrt(11329)*(177 - sqrt(11329))**0.5 + 1.42720405138895e-16*(177 - sqrt(11329))**0.5 + 0.00149797535073503*sqrt(11329)*(sqrt(11329) + 177)**0.5, -0.00296474288166307*sqrt(11329)*(177 - sqrt(11329))**0.5 + 0.353553390593274*(177 - sqrt(11329))**0.5 + 0.00296474288166308*sqrt(11329)*(sqrt(11329) + 177)**0.5 + 0.353553390593274*(sqrt(11329) + 177)**0.5]])

In [30]:
import sympy as sp

# Define matrix A
A = sp.Matrix([[41, 24], [24, 136]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = A.diagonalize()

# Eigenvalue decomposition
P, D = A.diagonalize()

P, D, P.inv()


(Matrix([
 [-sqrt(11329)/48 - 95/48, -95/48 + sqrt(11329)/48],
 [                      1,                       1]]),
 Matrix([
 [177/2 - sqrt(11329)/2,                     0],
 [                    0, sqrt(11329)/2 + 177/2]]),
 Matrix([
 [(-24*sqrt(11329) - 2280)/(95*sqrt(11329) + 11329), 1152/(95*sqrt(11329) + 11329)],
 [                             24*sqrt(11329)/11329,    95*sqrt(11329)/22658 + 1/2]]))

In [31]:
sp.Matrix([ [177/2 - sp.sqrt(11329)/2,                     0], [                    0, sp.sqrt(11329)/2 + 177/2]])@sp.Matrix([ [177/2 - sp.sqrt(11329)/2,                     0], [                    0, sp.sqrt(11329)/2 + 177/2]])

Matrix([
[(88.5 - sqrt(11329)/2)**2,                         0],
[                        0, (sqrt(11329)/2 + 88.5)**2]])

In [ ]:
import numpy as np
from scipy import linalg

A = np.array([[41, 24],
              [24, 136]])

B = linalg.sqrtm(A)

print(B)
print(B@B)

U = linalg.cholesky(A)
print(U)
print(U.transpose()@U)

[[ 6.2602777  1.3449624]
 [ 1.3449624 11.584087 ]]
[[ 41.000004  24.      ]
 [ 24.       136.      ]]
[[ 6.40312424  3.74817029]
 [ 0.         11.04315261]]
[[ 41.  24.]
 [ 24. 136.]]
